# .github/workflows/deploy.yml

# 이 자동화 작업의 이름을 정합니다.
name: Deploy to Dothome FTP

# 어떤 상황에서 이 작업을 실행할지 정합니다.
# main 브랜치에 push 이벤트가 발생했을 때 실행됩니다.
on:
  push:
    branches:
      - main

# 실제 실행될 작업들을 정의합니다.
jobs:
  deploy:
    # 이 작업이 실행될 가상 환경을 지정합니다.
    runs-on: ubuntu-latest

    # 작업의 단계(순서)를 나열합니다.
    steps:
      # 1. 깃허브 저장소의 코드를 가상 환경으로 내려받습니다.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. FTP를 이용해 닷홈 서버로 파일을 업로드합니다.
      # 유명한 FTP 배포 액션을 사용합니다.
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # 닷홈 서버 주소 (Secrets에서 가져옴)
          server: ${{ secrets.FTP_SERVER }}
          # 닷홈 아이디 (Secrets에서 가져옴)
          username: ${{ secrets.FTP_USERNAME }}
          # 닷홈 비밀번호 (Secrets에서 가져옴)
          password: ${{ secrets.FTP_PASSWORD }}
          # 업로드할 서버 경로 (보통 /html 입니다)
          server-dir: /html/